apiVersion: v1
kind: Service
metadata:
  name: chunk-upload-service
spec:
  selector:
    app: chunk-upload
  ports:
    - protocol: TCP
      port: 8080         # The port frontend will call
      targetPort: 8080   # The port your pod container exposes
  type: NodePort
